# Generated by Django 4.0.4 on 2022-06-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_correct_option_alter_question_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mode',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], default=('BASIC', 'BASIC'), max_length=40),
        ),
    ]
