# Generated by Django 4.0.4 on 2022-06-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='exert',
            field=models.TextField(default=''),
        ),
    ]
